### 固有値分解 (Eigenvalue Decomposition)

2x2行列の固有値分解を考えます。行列 $\mathbf{A}$ が固有値と固有ベクトルを持つ場合：
$ \mathbf{A} \mathbf{x}_1 = \lambda_1 \mathbf{x}_1, \quad \mathbf{A} \mathbf{x}_2 = \lambda_2 \mathbf{x}_2 $

行列 $\mathbf{A}$ を次のように分解します：
$ \mathbf{A} [\mathbf{x}_1, \mathbf{x}_2] = [\mathbf{x}_1, \mathbf{x}_2]
\begin{bmatrix}
\lambda_1 & 0 \\
0 & \lambda_2
\end{bmatrix} $

このとき、
$ \mathbf{P} = [\mathbf{x}_1, \mathbf{x}_2], \quad \mathbf{\Lambda} =
\begin{bmatrix}
\lambda_1 & 0 \\
0 & \lambda_2
\end{bmatrix} $


固有値分解の式は以下のようになります：
$ \mathbf{A} = \mathbf{P} \mathbf{\Lambda} \mathbf{P}^{-1} $

これは、対角化可能な行列に適用され、固有ベクトルが線形独立である場合に使われます。固有値分解は行列の性質を解析する強力な手法です。
### 固有値分解に基づく性質

#### 1. 行列の冪
$ \mathbf{A}^k = \mathbf{P} \mathbf{\Lambda} \mathbf{P}^{-1} \mathbf{P} \mathbf{\Lambda} \mathbf{P}^{-1} \cdots = \mathbf{P} \mathbf{\Lambda}^k \mathbf{P}^{-1}
 $

ここで、$\mathbf{\Lambda}^k$ は対角行列で、各要素は $\lambda_i^k$ です。
$ \mathbf{\Lambda}^k =
\begin{bmatrix}
\lambda_1^k & 0 & \cdots & 0 \\
0 & \lambda_2^k & \cdots & 0 \\
\vdots & \vdots & \ddots & \vdots \\
0 & 0 & \cdots & \lambda_m^k
\end{bmatrix} $




### 例題１）


3×3の行列を対角化し、そのべき乗を計算する例題を以下に作成し、その解法を示します。

### 例題

行列 $ A $ を次のように定義します。

$$
A =
\begin{bmatrix}
4 & 1 & 0 \\
0 & 2 & 0 \\
0 & 0 & 3
\end{bmatrix}
$$

この行列を対角化し、行列 $ A^5 $ を計算してください。

### 解法

#### 1. 固有値の計算

行列 $ A $ の固有値を求めます。固有値 $\lambda$ は、以下の特性方程式から求められます。

$$
\det(A - \lambda I) = 0
$$

計算を行います。

$$
A - \lambda I =
\begin{bmatrix}
4 - \lambda & 1 & 0 \\
0 & 2 - \lambda & 0 \\
0 & 0 & 3 - \lambda
\end{bmatrix}
$$

この行列の行列式は次のように計算されます。

$$
\det(A - \lambda I) = (4 - \lambda)(2 - \lambda)(3 - \lambda)
$$

これをゼロとします。

$$
(4 - \lambda)(2 - \lambda)(3 - \lambda) = 0
$$

したがって、固有値は $\lambda_1 = 4$, $\lambda_2 = 2$, $\lambda_3 = 3$ です。

#### 2. 固有ベクトルの計算

次に、各固有値に対応する固有ベクトルを求めます。

1. 固有値 $\lambda_1 = 4$ の場合：

   $$
   (A - 4I)\vec{v} = 0 \implies
   \begin{bmatrix}
   0 & 1 & 0 \\
   0 & -2 & 0 \\
   0 & 0 & -1
   \end{bmatrix}
   \vec{v} = 0
   $$

   上の行列から、固有ベクトルは $\vec{v}_1 = \begin{bmatrix} 1 \\ 0 \\ 0 \end{bmatrix}$ となります。

2. 固有値 $\lambda_2 = 2$ の場合：

   $$
   (A - 2I)\vec{v} = 0 \implies
   \begin{bmatrix}
   2 & 1 & 0 \\
   0 & 0 & 0 \\
   0 & 0 & 1
   \end{bmatrix}
   \vec{v} = 0
   $$

   この場合、固有ベクトルは $\vec{v}_2 = \begin{bmatrix} 0 \\ 1 \\ 0 \end{bmatrix}$ となります。

3. 固有値 $\lambda_3 = 3$ の場合：

   $$
   (A - 3I)\vec{v} = 0 \implies
   \begin{bmatrix}
   1 & 1 & 0 \\
   0 & -1 & 0 \\
   0 & 0 & 0
   \end{bmatrix}
   \vec{v} = 0
   $$

   この場合、固有ベクトルは $\vec{v}_3 = \begin{bmatrix} 0 \\ 0 \\ 1 \end{bmatrix}$ となります。

#### 3. 行列の対角化

固有ベクトルを使って、行列 $ P $ と対角行列 $ D $ を作ります。

$$
P =
\begin{bmatrix}
1 & 0 & 0 \\
0 & 1 & 0 \\
0 & 0 & 1
\end{bmatrix}, \quad
D =
\begin{bmatrix}
4 & 0 & 0 \\
0 & 2 & 0 \\
0 & 0 & 3
\end{bmatrix}
$$

対角化の関係式は次の通りです。

$$
A = PDP^{-1}
$$

#### 4. $ A^5 $ の計算

行列のべき乗は、対角化を利用して以下のように計算できます。

$$
A^5 = PD^5P^{-1}
$$

ここで、対角行列のべき乗 $ D^5 $ は、各対角成分をそれぞれ5乗することで得られます。

$$
D^5 =
\begin{bmatrix}
4^5 & 0 & 0 \\
0 & 2^5 & 0 \\
0 & 0 & 3^5
\end{bmatrix}
=
\begin{bmatrix}
1024 & 0 & 0 \\
0 & 32 & 0 \\
0 & 0 & 243
\end{bmatrix}
$$

したがって、

$$
A^5 = P D^5 P^{-1} =
\begin{bmatrix}
1024 & 0 & 0 \\
0 & 32 & 0 \\
0 & 0 & 243
\end{bmatrix}
$$

### 結果

$$
A^5 =
\begin{bmatrix}
1024 & 0 & 0 \\
0 & 32 & 0 \\
0 & 0 & 243
\end{bmatrix}
$$

これが行列 $ A $ の5乗です。


In [1]:
import numpy as np
from scipy.linalg import inv

# 行列 A の定義
A = np.array([
    [4, 1, 0],
    [0, 2, 0],
    [0, 0, 3]
])

# 固有値と固有ベクトルを計算
eigenvalues, eigenvectors = np.linalg.eig(A)

# 固有ベクトルの行列 P とその逆行列 P_inv を定義
P = eigenvectors
P_inv = inv(P)

# 固有値を使って対角行列 D を定義
D = np.diag(eigenvalues)

# D の 5 乗を計算
D_power_5 = np.diag(eigenvalues**5)

# A の 5 乗を計算
A_power_5 = P @ D_power_5 @ P_inv

# 結果の表示
print("行列 A の 5 乗:\n", A_power_5)


行列 A の 5 乗:
 [[1024.  496.    0.]
 [   0.   32.    0.]
 [   0.    0.  243.]]


#### 2. 逆行列
$ \mathbf{A}^{-1} = (\mathbf{P} \mathbf{\Lambda} \mathbf{P}^{-1})^{-1} = \mathbf{P} \mathbf{\Lambda}^{-1} \mathbf{P}^{-1} $

ここで、$\mathbf{\Lambda}^{-1}$ は次のように計算されます：
$ \mathbf{\Lambda}^{-1} =
\begin{bmatrix}
\frac{1}{\lambda_1} & 0 & \cdots & 0 \\
0 & \frac{1}{\lambda_2} & \cdots & 0 \\
\vdots & \vdots & \ddots & \vdots \\
0 & 0 & \cdots & \frac{1}{\lambda_m}
\end{bmatrix} $

#### 3. 行列式
$ \text{det}(\mathbf{A}) = \text{det}(\mathbf{P} \mathbf{\Lambda} \mathbf{P}^{-1}) = \text{det}(\mathbf{P}) \text{det}(\mathbf{\Lambda}) \text{det}(\mathbf{P}^{-1}) = \prod_{i=1}^{n} \lambda_i $

#### 4. トレース
$ \text{tr}(\mathbf{A}) = \text{tr}(\mathbf{P} \mathbf{\Lambda} \mathbf{P}^{-1}) = \text{tr}(\mathbf{\Lambda}) = \lambda_1 + \lambda_2 + \cdots + \lambda_n
 $

#### 5. Rank-deficient 行列

行列が Rank-deficient である場合、$\text{det}(\mathbf{A}) = 0$ であり、少なくとも1つの固有値が $0$ になります。

---



### その他の固有値に関する性質

#### 1. 対称行列の性質

- 対称行列 $\mathbf{A}$ の固有値は $\mathbf{A}$ の固有値と一致します。
$ \text{det}(\mathbf{A} - \lambda \mathbf{I}) = \text{det}((\mathbf{A} - \lambda \mathbf{I})^T) = \text{det}(\mathbf{A}^T - \lambda \mathbf{I})
 $

#### 2. 直交行列

- 直交行列 $\mathbf{A}$ の場合、固有値は $\lambda_i = \pm 1$ です。
$ \mathbf{Qx} = \lambda \mathbf{x}, \quad (\mathbf{Qx})^T \mathbf{Qx} = \lambda^2 \|\mathbf{x}\|^2 = \|\mathbf{Qx}\|^2 = \|\mathbf{x}\|^2 $

#### 3. 正定値半正定値行列 (Positive Semi-Definite Matrix)

- $\mathbf{A}$ が半正定値 (P.S.D.) の場合、すべての固有値は非負です。
$ \lambda_i \geq 0 $

#### 4. 対角化可能な行列

- 対角化可能な行列の0でない固有値の数は行列のランクに等しい。
$ \text{rank}(\mathbf{A}) = \text{non-zero eigenvalues} $

---

これらの性質は、行列の固有値や構造に基づいて行列の行動を予測するための重要なツールとなります。特に、固有値分解は行列を対角化し、行列の計算を簡略化するための基本的な手法です。
### 対称行列の固有値分解 (Symmetric Matrix)

対称行列 $\mathbf{A}$ は必ず対角化可能です。

- $\mathbf{A} = \mathbf{A}^T$
- $\mathbf{A} = \mathbf{Q} \mathbf{\Lambda} \mathbf{Q}^T$
- $\mathbf{A} = \mathbf{P} \mathbf{\Lambda} \mathbf{P}^{-1}$

ここで、$\mathbf{Q}$ は直交行列で $\mathbf{Q}^{-1} = \mathbf{Q}^T$ です。

#### 固有値分解の詳細

行列 $\mathbf{A}$ を次のように固有値分解します：
$ \mathbf{A} =
\begin{bmatrix}
\mathbf{q}_1 & \mathbf{q}_2 & \mathbf{q}_3
\end{bmatrix}
\begin{bmatrix}
\lambda_1 & 0 & 0 \\
0 & \lambda_2 & 0 \\
0 & 0 & \lambda_3
\end{bmatrix}
\begin{bmatrix}
\mathbf{q}_1^T \\
\mathbf{q}_2^T \\
\mathbf{q}_3^T
\end{bmatrix} $

これにより、次のように展開されます：
$ \mathbf{A} = \lambda_1 \mathbf{q}_1 \mathbf{q}_1^T + \lambda_2 \mathbf{q}_2 \mathbf{q}_2^T + \lambda_3 \mathbf{q}_3 \mathbf{q}_3^T $

- 各項 $\lambda_i \mathbf{q}_i \mathbf{q}_i^T$ はランク1の行列で、$\lambda_i$ が小さい場合は圧縮されてゼロに近づきます。

---

### データ圧縮としての解釈

行列 $\mathbf{A}$ は各固有ベクトルと対応する固有値の組み合わせとして表現されます。例えば、3x3行列の場合：
$ \mathbf{A} = \lambda_1 \mathbf{q}_1 \mathbf{q}_1^T + \lambda_2 \mathbf{q}_2 \mathbf{q}_2^T + \lambda_3 \mathbf{q}_3 \mathbf{q}_3^T $

ベクトル $\mathbf{x}$ に対する作用 $\mathbf{A}\mathbf{x}$ も同様に展開できます：
$ \mathbf{A} \mathbf{x} = \lambda_1 \mathbf{q}_1 (\mathbf{q}_1^T \mathbf{x}) + \lambda_2 \mathbf{q}_2 (\mathbf{q}_2^T \mathbf{x}) + \lambda_3 \mathbf{q}_3 (\mathbf{q}_3^T \mathbf{x}) $

これにより、$\mathbf{A} (\mathbf{A}^T \mathbf{A})^{-1} \mathbf{A}^T$ は射影行列 (Projection Matrix) となります。

---

### 具体例

ベクトル $\mathbf{x}$ が次のように与えられる場合：
$ \mathbf{x} =
\begin{bmatrix}
-1 \\
2 \\
3
\end{bmatrix}
= 1
\begin{bmatrix}
1 \\
0 \\
0
\end{bmatrix}
+ 2
\begin{bmatrix}
0 \\
1 \\
0
\end{bmatrix}
+ 3
\begin{bmatrix}
0 \\
0 \\
1
\end{bmatrix} $

ここで、$\lambda_1 = \lambda_2 = \lambda_3 = 1$ であれば、
$ \mathbf{A} \mathbf{x} = \mathbf{q}_1 (\mathbf{q}_1^T \mathbf{x}) + \mathbf{q}_2 (\mathbf{q}_2^T \mathbf{x}) + \mathbf{q}_3 (\mathbf{q}_3^T \mathbf{x}) = \mathbf{x} $

---

### 直交行列による対角化
$ \mathbf{A} = \mathbf{Q} \mathbf{\Lambda} \mathbf{Q}^T $

- ここで、$\mathbf{Q}$ は直交行列であり、$\mathbf{Q} \mathbf{Q}^T = \mathbf{I}$ です。

この式により、行列 $\mathbf{A}$ の各方向の変換が理解できます。特に、対称行列は常に直交行列によって対角化できるため、計算が容易です。